name: 'Run tests and deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-and-test:
    name: 'Run tests and deploy'
    runs-on: ubuntu-latest
    environment: dev
    concurrency: test_and_deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.14.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: node-cache-${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            node-cache-${{ runner.os }}-pnpm

      - name: Run end-to-end tests
        id: e2eTests
        uses: cypress-io/github-action@v4
        with:
          install: false
          working-directory: ./end-to-end-tests
          spec: |
            cypress/e2e/**/*.spec.ts