name: 'Run tests and deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-and-test:
    name: 'Run tests and deploy'
    runs-on: ubuntu-latest
    environment: dev
    concurrency: test_and_deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.14.0

      - name: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Run end-to-end tests
        id: e2eTests
        run: pnpm i && pnpm run install:cypress && pnpm run test
        working-directory: ./end-to-end-tests